language: csharp
mono: none
dotnet: 2.1.300
os:
  - linux
  - osx
script:
  - dotnet build 
  - dotnet test DotNetCore.Tools.DotNetCoreInstallerTests/DotNetCore.Tools.DotNetCoreInstallerTests.csproj /p:CollectCoverage=true
